CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;

ALTER TABLE public.coffee_taps
  ADD COLUMN IF NOT EXISTS anonymized_at TIMESTAMPTZ;

ALTER TABLE public.coffee_taps
  ALTER COLUMN visitor_id DROP NOT NULL;

ALTER TABLE public.coffee_taps
  DROP CONSTRAINT IF EXISTS coffee_taps_visitor_id_key;

CREATE UNIQUE INDEX IF NOT EXISTS coffee_taps_active_visitor_id_idx
  ON public.coffee_taps (visitor_id)
  WHERE visitor_id IS NOT NULL;

ALTER TABLE public.coffee_taps
  DROP CONSTRAINT IF EXISTS coffee_taps_identifier_state_check;

ALTER TABLE public.coffee_taps
  ADD CONSTRAINT coffee_taps_identifier_state_check CHECK (
    (visitor_id IS NOT NULL AND anonymized_at IS NULL)
    OR (visitor_id IS NULL AND anonymized_at IS NOT NULL)
  );

CREATE TABLE IF NOT EXISTS public.privacy_retention_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ran_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  rate_limit_rows_deleted BIGINT NOT NULL DEFAULT 0 CHECK (rate_limit_rows_deleted >= 0),
  coffee_identifiers_anonymized BIGINT NOT NULL DEFAULT 0 CHECK (coffee_identifiers_anonymized >= 0)
);

CREATE INDEX IF NOT EXISTS privacy_retention_runs_ran_at_idx
  ON public.privacy_retention_runs (ran_at DESC);

ALTER TABLE public.privacy_retention_runs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.privacy_retention_runs FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.privacy_retention_runs TO service_role;

CREATE OR REPLACE FUNCTION public.enforce_privacy_retention()
RETURNS TABLE (
  rate_limit_rows_deleted BIGINT,
  coffee_identifiers_anonymized BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_now TIMESTAMPTZ := clock_timestamp();
  v_rate_limit_rows_deleted BIGINT := 0;
  v_coffee_identifiers_anonymized BIGINT := 0;
BEGIN
  DELETE FROM public.contact_rate_limits
  WHERE updated_at < v_now - interval '7 days';
  GET DIAGNOSTICS v_rate_limit_rows_deleted = ROW_COUNT;

  UPDATE public.coffee_taps
  SET
    visitor_id = NULL,
    anonymized_at = v_now
  WHERE visitor_id IS NOT NULL
    AND created_at < v_now - interval '30 days';
  GET DIAGNOSTICS v_coffee_identifiers_anonymized = ROW_COUNT;

  DELETE FROM public.privacy_retention_runs
  WHERE ran_at < v_now - interval '90 days';

  INSERT INTO public.privacy_retention_runs (
    ran_at,
    rate_limit_rows_deleted,
    coffee_identifiers_anonymized
  )
  VALUES (
    v_now,
    v_rate_limit_rows_deleted,
    v_coffee_identifiers_anonymized
  );

  RETURN QUERY SELECT v_rate_limit_rows_deleted, v_coffee_identifiers_anonymized;
END;
$$;

REVOKE ALL ON FUNCTION public.enforce_privacy_retention() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enforce_privacy_retention() TO service_role;

CREATE OR REPLACE FUNCTION public.get_privacy_retention_status()
RETURNS TABLE (
  last_run_at TIMESTAMPTZ,
  is_current BOOLEAN
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    max(ran_at) AS last_run_at,
    coalesce(max(ran_at) >= clock_timestamp() - interval '36 hours', false) AS is_current
  FROM public.privacy_retention_runs;
$$;

REVOKE ALL ON FUNCTION public.get_privacy_retention_status() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_privacy_retention_status() TO service_role;

SELECT cron.unschedule(jobid)
FROM cron.job
WHERE jobname = 'privacy-retention-daily';

SELECT cron.schedule(
  'privacy-retention-daily',
  '17 3 * * *',
  'SELECT public.enforce_privacy_retention();'
);

SELECT public.enforce_privacy_retention();
